### ISSUE TITLE
How to import safely on ios?

### ISSUE THREAD

**Issue by Noitidart** [ramilushev/react-native-background-color#6]
At the top of my file I have:

    import BackgroundColor from 'react-native-background-color';

Now this works on Android, but in iOS it is giving me error:

```
error: bundling failed: Error: While trying to resolve module `react-native-background-color` from file `/Users/noitidart/Documents/Did/App/AppCover/index.ios.js`, the package `/Users/noitidart/Documents/Did/node_modules/react-native-background-color/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/Users/noitidart/Documents/Did/node_modules/react-native-background-color/index`. Indeed, none of these files exist:

  * `/Users/noitidart/Documents/Did/node_modules/react-native-background-color/index(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)`
  * `/Users/noitidart/Documents/Did/node_modules/react-native-background-color/index/index(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)`
    at ResolutionRequest.resolveDependency (/Users/noitidart/Documents/Did/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:95:15)
    at DependencyGraph.resolveDependency (/Users/noitidart/Documents/Did/node_modules/metro/src/node-haste/DependencyGraph.js:238:485)
    at Object.resolve (/Users/noitidart/Documents/Did/node_modules/metro/src/lib/transformHelpers.js:180:25)
    at dependencies.map.result (/Users/noitidart/Documents/Did/node_modules/metro/src/DeltaBundler/traverseDependencies.js:311:29)
    at Array.map (<anonymous>)
    at resolveDependencies (/Users/noitidart/Documents/Did/node_modules/metro/src/DeltaBundler/traverseDependencies.js:307:16)
    at /Users/noitidart/Documents/Did/node_modules/metro/src/DeltaBundler/traverseDependencies.js:164:33
    at Generator.next (<anonymous>)
    at step (/Users/noitidart/Documents/Did/node_modules/metro/src/DeltaBundler/traverseDependencies.js:266:307)
    at /Users/noitidart/Documents/Did/node_modules/metro/src/DeltaBundler/traverseDependencies.js:266:467
```

I was hoping to avoid creating platform specific files.

**Comment by lsirdevan** [comment]
For anyone that wanted to use this repo, i've just conditionally required the module like so:

```
import React from "react";
import { Alert, Linking, Platform } from "react-native";

class Test extends React.Component {
    constructor(props) {
        super(props);

        if (Platform.OS !== "ios") {
            let BackgroundColor = require("react-native-background-color");
            BackgroundColor.setColor("#FFFFFF");
        }
    }
}
```

This way it doesn't crash iOS and functions correctly on Android.

**Comment by lsirdevan** [comment]
Merging #8 will fix this. 

This does not add support for iOS, just gets around the error. To use this library you should import conditionally:

import React from "react";
import { Alert, Linking, Platform } from "react-native";

```
class Background extends React.Component {
    constructor(props) {
        super(props);
        if (Platform.OS !== "ios") {
            let BackgroundColor = require("react-native-background-color");

            BackgroundColor.setColor("#FFFFFF");
        }
    }
}
```

**Comment by Noitidart** [comment]
Thanks for sharing! Can also use a `.android.js` if you want.

**Comment by haveamission** [comment]
This is simply not working for me.

I have this in my app:

if (Platform.OS !== "ios") {
  var BackgroundColor = require("react-native-background-color");
}

However when I try to bundle in iOS, I get this:

error: bundling failed: Error: While trying to resolve module `react-native-background-color` from file `/Users/andy/Desktop/Projects/shoployalrn/components/main/Layout.js`, the package `/Users/andy/Desktop/Projects/shoployalrn/node_modules/react-native-background-color/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/Users/andy/Desktop/Projects/shoployalrn/node_modules/react-native-background-color/index`. Indeed, none of these files exist:

When I comment out the line, no issue
